### ISSUE TITLE
A Regional Admin or Lawyer Can Add a Review

### ISSUE THREAD

**Issue by CZagrobelny** [rubyforgood/new_sanctuary_asylum#10]
Database Changes:
Add a reviews table, which belongs_to draft.
The table should have a column 'notes' (text)

On the Friend detail page, a Regional Admin and a Lawyer will see a link to 'Add a Review' below each Application Draft (if the Regional Admin or Lawyer has not already created a review for that application draft).  When they click on 'Add a Review' they should be redirected to a form with a large text area for the review 'notes'.

On the Friend detail page (both for regional admins/lawyers AND the separate page for non-primary community admins AND the separate page for non-primary community users), once a review has been created, it should be displayed according to the below mock up.  The 'Review by [reviewer name] ([reviewer role])' should link to a show page for the review (this will change later when we introduce edit functionality).
![mockup 3](https://user-images.githubusercontent.com/3056607/40936040-fa1206b6-6807-11e8-925b-856c584d378f.png)

When a review is added, the following should occur:
- the draft status should change to 'changes_requested'
- the application status should change to 'changes_requested'
- the community users associated with the friend and the community admins for the friend should receive an email notification:
'Review submitted for [Friend first name]'s [application type] application draft'

Additional changes:
- the draft with the associated application should no longer be editable by anyone (remove Edit link and restrict access to edit/update in the controller)

**Comment by scooter-dangle** [comment]
Note: Per discussion with @CZagrobelny, the `Add Review` link should _not_ disappear once there are reviews (as implied in the image above)—new reviews can _always_ be added regardless of preëxisting reviews.

**Comment by Thomascountz** [comment]
- [ ] Add `reviews` table with a `:text, :notes` column
- [ ] Create a `Review` model
- [ ] On friend details page, regional_admin and lawyer will see a link to "Add a Review"
- [ ] Create review form
- [ ] Create a `ReviewsController`
- [ ] Update friend view for all users to display "status"

**Comment by Thomascountz** [comment]
Non-primary Volunteer & Accompaniment Leader - `communities/nyc/fiend/:id`
See "Reviewed by..."

Non-primary Community Admin - "Documents" & "Manage Documents"
See "Reviewed by..." 

Regional Admin & Lawyer - New View
`RemoteClinicController`
See "All Reviews"
Edit "Their reviews"
Add "Review"

**Comment by Thomascountz** [comment]
`dependent :destroy` review?

**Comment by Thomascountz** [comment]
What `User` roles have access to the `/admin` paths?

**Comment by Thomascountz** [comment]
After a `Review` is added to a `Draft`/`Application`, set the `draft.status` and `application.status` to `:changes_requested"

**Comment by Thomascountz** [comment]
- [ ]  Redirect to `#documents` page after review is submitted
- [ ] Update `draft.status` to `changes_requested`
- [ ] Update `draft.application.status` to `changes_requested`

**Comment by Thomascountz** [comment]
TODO:

- [ ] The community users associated with the friend and the community admins for the friend should receive an email notification: 'Review submitted for [Friend first name]'s [application type] application draft'
