### ISSUE TITLE
Regional Admin Assigns a Lawyer to a Friend

### ISSUE THREAD

**Issue by CZagrobelny** [rubyforgood/new_sanctuary_asylum#16]
When a Regional admin views a Friend's application drafts, they should see a searchable multi select field below the application draft section to add lawyers for the Friend for application review.  See the bottom part of this mockup:

![mockup 3](https://user-images.githubusercontent.com/3056607/40935656-c7a1f5ac-6806-11e8-93ac-e27d4fed24c1.png)

Also, when a regional admin is editing a lawyer record, we should add a multiselect like this to that form.  It would show which friends the lawyer had access to.

When a lawyer is assigned to a friend, the lawyer should receive an email notification:
'You have been assigned to review [Friend first name]'s applications'

**Comment by CZagrobelny** [comment]
@ashag wanted to give you a heads up that I made a few changes in the master branch for the remote clinic lawyer functionality (cleaning up the header, adding fields to forms for consistency, and removing the invite user link (since this is now happening through communities).  I also added methods to get all the remote clinic lawyers for a friend and all the friends assigned to a remote clinic lawyer.  'remote_clinic_lawyers' in the friend model. And 'remote_clinic_friends' in the user model.  Thought these might come in handy for this issue.

**Comment by CZagrobelny** [comment]
@ashag I'm checking in with everyone about their current Ruby for Good issues for NSC.  I am hoping to demo the software for NSC staff members in the first week of July and wondered if you think the two issues you are working on (#16 & #17) could have PRs in by next Friday?  Let me know if that will work with your schedule and workload, thanks!!!!

**Comment by ashag** [comment]
@CZagrobelny Slacked you but responding here also. I've had a super busy work week but I'll try to get at least one issue finished, if not both. I'll keep you updated.

**Comment by ashag** [comment]
@CZagrobelny just want to clarify, does the multiselect only include remote clinic lawyers or does it also include in-person lawyers in that friend's community?

**Comment by CZagrobelny** [comment]
@ashag the multiselect should only include remote clinic lawyers.  Thanks!!!

**Comment by ashag** [comment]
@CZagrobelny update on #16 and #17: I'll open a PR for both by tomorrow. They are pretty much ready except not much styling and I still need to write some tests.
