### ISSUE TITLE
Migrate to CircleCI 2.0 before it's sunset at end of August

### ISSUE THREAD

**Issue by scooter-dangle** [rubyforgood/new_sanctuary_asylum#27]
Per https://circleci.com/docs/2.0/faq/#can-i-try-circleci-20-while-still-using-10, we need to upgrade to CircleCI 2.0, which requires changes to our CircleCI configuration.

Sundry extra
------------

Per https://github.com/rubyforgood/new_sanctuary_asylum/pull/24#issuecomment-395885254, will also add `rake bundle:audit` as a step in the updated config.

**Comment by CZagrobelny** [comment]
@scooter-dangle thank you for creating this issue!!!
